# Generated by Django 3.2.2 on 2023-03-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, unique=True)),
                ('location', models.CharField(default='', max_length=64)),
                ('wins', models.SmallIntegerField()),
                ('losses', models.SmallIntegerField()),
            ],
        ),
    ]
