# Generated by Django 3.2.2 on 2023-03-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
