# Generated by Django 3.2.2 on 2023-03-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0002_auto_20230317_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='match',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
    ]
