# Generated by Django 3.2.2 on 2023-03-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='match',
        ),
    ]
