# Generated by Django 3.2.2 on 2023-03-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='location',
        ),
        migrations.RemoveField(
            model_name='team',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
        migrations.AddField(
            model_name='team',
            name='primary_color',
            field=models.CharField(default='ffffff', max_length=6),
        ),
        migrations.AddField(
            model_name='team',
            name='secondary_color',
            field=models.CharField(default='ffffff', max_length=6),
        ),
    ]
