# Generated by Django 3.2.2 on 2023-03-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20230323_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(default='NA', max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
