# Generated by Django 3.2.2 on 2023-03-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
