# Generated by Django 3.2.2 on 2023-03-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20230321_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
