# Generated by Django 3.2.2 on 2023-03-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
