# Generated by Django 3.2.2 on 2023-03-21 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_match'),
        ('matches', '0004_auto_20230321_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='time',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team', to='teams.team'),
        ),
    ]
