# Generated by Django 3.2.2 on 2023-03-24 00:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_team_abbreviation'),
        ('matches', '0005_auto_20230321_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='competition_stage',
            field=models.CharField(default='TBD', max_length=64),
        ),
        migrations.AddField(
            model_name='match',
            name='matchup',
            field=models.CharField(default='TBD', max_length=32),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(db_column='away_team', default='TBD', on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(db_column='home_team', default='TBD', on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(default='TBD', max_length=64),
        ),
    ]
