# Generated by Django 3.2.2 on 2023-03-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20230323_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date_time',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
